### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by JayFoxRox** [mnadareski/WiseUnpacker#2]
I need to extract some WISE installer files from the late 90ies on a Linux machine.
I'm unable to find a functional solution, and this looks to be one of the most promising options.

Mono support would be excellent (or if it already works, better documentation).

I tried looking into it myself but was unable to figure out how to do this (I have little idea about C# and .NET, so I'm not suitable to work on it).

**Comment by JayFoxRox** [comment]
I was incorrectly using `xbuild` and `dotnet msbuild`; I've now tried `dotnet build` and that works!
I can run `mono ./Test/bin/Debug/net48/Test.exe /tmp/wise-setup.exe`  and it will work.

However, it does incorrectly emit filenames like `path1\path2\file.bin` in the root, rather than emitting the files to folder `path1`, subfolder `path2`, `file.bin`.
So this project needs some code to handle translation of backslash to forward slash.

**Comment by mnadareski** [comment]
You should be able to run this with .NET Core 3.1 on anything that would normally run .NET Framework 4.8 on `mono`. That should clear up any path issues, since it will use what is native to the system instead.

**Comment by JayFoxRox** [comment]
> You should be able to run this with .NET Core 3.1 on anything that would normally run .NET Framework 4.8 on mono.

I can run it, but the path problem persists, because of differences between Linux and Windows filesystem handling.

> That should clear up any path issues, since it will use what is native to the system instead.

The problem is part of WiseUnpacker / the wise file format. It's shouldn't be specific to some C# runtime.

wise assumes WIN32 and the wise-packed EXE file contains hardcode paths with backslashes in them. C# does not do much with those and just forwards them to the OS.
`Path.Combine` itself will only concatenate the path with the platform-appropriate forward-slash but it won't handle any path separators (back-slashes) in the path that came from wise.
On Windows, the wise path separator (`\`) will be interpreted as path separators; on Linux it will be considered part of the filename.

I can fix it by replacing https://github.com/mnadareski/WiseUnpacker/blob/5561dfae7790a42379add9638ef1b4aff5f29365/WiseUnpacker/WiseUnpacker.cs#L706

with this:

```cs
                           newName = newName.Replace("%", string.Empty);

                            /* Temporarily switch escaped-backslash to % */
                            newName = newName.Replace("\\\\", "%");

                            /* Replace separator with forward-slash for POSIX */
                            newName = newName.Replace("\\", "/");

                            /* Recover escaped-backslashes */
                            newName = newName.Replace("%", "\\");
```

Note that I needed a hack, so an actual backslash in filenames can still occur. I abused the `%` symbol as a placeholder.

The [more correct solution would probably be to replace `/` in my code by `Path.DirectorySeparatorChar`](https://stackoverflow.com/a/20708301).

**Comment by mnadareski** [comment]
I'll give it a shot to fix it up. I'm fairly certain you're the only person outside of my own projects who has even looked at this until now, so I'm not surprised that this slipped through.

**Comment by mnadareski** [comment]
Odd note, I think that the usage of `\\\\` actually is an empty directory and not an escaped `\` in terms of Wise. I could be 100% wrong there, but I'm pretty sure that why it can be collapsed.

**Comment by mnadareski** [comment]
Give this a shot when you get a chance: https://github.com/mnadareski/WiseUnpacker/commit/78e1cc0a02fd8ace541b0e50887e0f1a5c48981a
