### ISSUE TITLE
WiseUnpacker in C or C++ for OpenHL

### ISSUE THREAD

**Issue by osen** [mnadareski/WiseUnpacker#3]
Hello there,

Firstly I would like to thank you for your brilliant tool. The ancient Half-Life (Steam) [installers](https://www.ausgamers.com/files/download/8448/steam-client-with-halflife-cache) use this format of Wise and it was fairly difficult to get them extracted simply on non-windows platforms and without i.e Wine.

I use it for this project: https://github.com/osen/openhl
These installers are a great way to be able to distribute the data legally (although obviously **using** the data is prohibited without a license).

However, I am looking to simplify the project further and reduce dependency on Python (waf) as well as Mono (WiseUnpacker) and bring everything in to homogeneous C and C++.

Before I start looking into implementing just the parts of your project required to extract the Half-Life data in C++, I just thought I should check with you if you have any early prototypes laying around in either C or C++?

Many thanks!

**Comment by mnadareski** [comment]
I don't program in either C or C++. Feel free to port from my code yourself or use the tools that I have based this project on, which, if I recall correctly, are already in C/C++.

**Comment by osen** [comment]
Many thanks for getting back to me.

I recall now why I used your project in the first place, the upstream projects you have based yours on are both written in (fairly crusty) pascal. Your code is more readable so I will use that as a reference.

Thanks again,
